# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nikolayk/wabts/wabt1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nikolayk/wabts/wabt1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikolayk/wabts/wabt1/CMakeFiles /home/nikolayk/wabts/wabt1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikolayk/wabts/wabt1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run-tests

# Build rule for target.
run-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run-tests
.PHONY : run-tests

# fast build rule for target.
run-tests/fast:
	$(MAKE) -f CMakeFiles/run-tests.dir/build.make CMakeFiles/run-tests.dir/build
.PHONY : run-tests/fast

#=============================================================================
# Target rules for targets named everything

# Build rule for target.
everything: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 everything
.PHONY : everything

# fast build rule for target.
everything/fast:
	$(MAKE) -f CMakeFiles/everything.dir/build.make CMakeFiles/everything.dir/build
.PHONY : everything/fast

#=============================================================================
# Target rules for targets named WASM_AST_LEXER_GEN_C

# Build rule for target.
WASM_AST_LEXER_GEN_C: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WASM_AST_LEXER_GEN_C
.PHONY : WASM_AST_LEXER_GEN_C

# fast build rule for target.
WASM_AST_LEXER_GEN_C/fast:
	$(MAKE) -f CMakeFiles/WASM_AST_LEXER_GEN_C.dir/build.make CMakeFiles/WASM_AST_LEXER_GEN_C.dir/build
.PHONY : WASM_AST_LEXER_GEN_C/fast

#=============================================================================
# Target rules for targets named wast-desugar

# Build rule for target.
wast-desugar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wast-desugar
.PHONY : wast-desugar

# fast build rule for target.
wast-desugar/fast:
	$(MAKE) -f CMakeFiles/wast-desugar.dir/build.make CMakeFiles/wast-desugar.dir/build
.PHONY : wast-desugar/fast

#=============================================================================
# Target rules for targets named wasm2wast

# Build rule for target.
wasm2wast: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wasm2wast
.PHONY : wasm2wast

# fast build rule for target.
wasm2wast/fast:
	$(MAKE) -f CMakeFiles/wasm2wast.dir/build.make CMakeFiles/wasm2wast.dir/build
.PHONY : wasm2wast/fast

#=============================================================================
# Target rules for targets named wast2wasm

# Build rule for target.
wast2wasm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wast2wasm
.PHONY : wast2wasm

# fast build rule for target.
wast2wasm/fast:
	$(MAKE) -f CMakeFiles/wast2wasm.dir/build.make CMakeFiles/wast2wasm.dir/build
.PHONY : wast2wasm/fast

#=============================================================================
# Target rules for targets named libwasm

# Build rule for target.
libwasm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libwasm
.PHONY : libwasm

# fast build rule for target.
libwasm/fast:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/build
.PHONY : libwasm/fast

#=============================================================================
# Target rules for targets named hexfloat_test

# Build rule for target.
hexfloat_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hexfloat_test
.PHONY : hexfloat_test

# fast build rule for target.
hexfloat_test/fast:
	$(MAKE) -f CMakeFiles/hexfloat_test.dir/build.make CMakeFiles/hexfloat_test.dir/build
.PHONY : hexfloat_test/fast

#=============================================================================
# Target rules for targets named wasmopcodecnt

# Build rule for target.
wasmopcodecnt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wasmopcodecnt
.PHONY : wasmopcodecnt

# fast build rule for target.
wasmopcodecnt/fast:
	$(MAKE) -f CMakeFiles/wasmopcodecnt.dir/build.make CMakeFiles/wasmopcodecnt.dir/build
.PHONY : wasmopcodecnt/fast

#=============================================================================
# Target rules for targets named wasm-interp

# Build rule for target.
wasm-interp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wasm-interp
.PHONY : wasm-interp

# fast build rule for target.
wasm-interp/fast:
	$(MAKE) -f CMakeFiles/wasm-interp.dir/build.make CMakeFiles/wasm-interp.dir/build
.PHONY : wasm-interp/fast

#=============================================================================
# Target rules for targets named wasmdump

# Build rule for target.
wasmdump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wasmdump
.PHONY : wasmdump

# fast build rule for target.
wasmdump/fast:
	$(MAKE) -f CMakeFiles/wasmdump.dir/build.make CMakeFiles/wasmdump.dir/build
.PHONY : wasmdump/fast

ast-lexer-gen.o: ast-lexer-gen.c.o

.PHONY : ast-lexer-gen.o

# target to build an object file
ast-lexer-gen.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/ast-lexer-gen.c.o
.PHONY : ast-lexer-gen.c.o

ast-lexer-gen.i: ast-lexer-gen.c.i

.PHONY : ast-lexer-gen.i

# target to preprocess a source file
ast-lexer-gen.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/ast-lexer-gen.c.i
.PHONY : ast-lexer-gen.c.i

ast-lexer-gen.s: ast-lexer-gen.c.s

.PHONY : ast-lexer-gen.s

# target to generate assembly for a file
ast-lexer-gen.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/ast-lexer-gen.c.s
.PHONY : ast-lexer-gen.c.s

ast-parser-gen.o: ast-parser-gen.c.o

.PHONY : ast-parser-gen.o

# target to build an object file
ast-parser-gen.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/ast-parser-gen.c.o
.PHONY : ast-parser-gen.c.o

ast-parser-gen.i: ast-parser-gen.c.i

.PHONY : ast-parser-gen.i

# target to preprocess a source file
ast-parser-gen.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/ast-parser-gen.c.i
.PHONY : ast-parser-gen.c.i

ast-parser-gen.s: ast-parser-gen.c.s

.PHONY : ast-parser-gen.s

# target to generate assembly for a file
ast-parser-gen.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/ast-parser-gen.c.s
.PHONY : ast-parser-gen.c.s

src/allocator.o: src/allocator.c.o

.PHONY : src/allocator.o

# target to build an object file
src/allocator.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/allocator.c.o
.PHONY : src/allocator.c.o

src/allocator.i: src/allocator.c.i

.PHONY : src/allocator.i

# target to preprocess a source file
src/allocator.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/allocator.c.i
.PHONY : src/allocator.c.i

src/allocator.s: src/allocator.c.s

.PHONY : src/allocator.s

# target to generate assembly for a file
src/allocator.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/allocator.c.s
.PHONY : src/allocator.c.s

src/apply-names.o: src/apply-names.c.o

.PHONY : src/apply-names.o

# target to build an object file
src/apply-names.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/apply-names.c.o
.PHONY : src/apply-names.c.o

src/apply-names.i: src/apply-names.c.i

.PHONY : src/apply-names.i

# target to preprocess a source file
src/apply-names.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/apply-names.c.i
.PHONY : src/apply-names.c.i

src/apply-names.s: src/apply-names.c.s

.PHONY : src/apply-names.s

# target to generate assembly for a file
src/apply-names.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/apply-names.c.s
.PHONY : src/apply-names.c.s

src/ast-parser-lexer-shared.o: src/ast-parser-lexer-shared.c.o

.PHONY : src/ast-parser-lexer-shared.o

# target to build an object file
src/ast-parser-lexer-shared.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/ast-parser-lexer-shared.c.o
.PHONY : src/ast-parser-lexer-shared.c.o

src/ast-parser-lexer-shared.i: src/ast-parser-lexer-shared.c.i

.PHONY : src/ast-parser-lexer-shared.i

# target to preprocess a source file
src/ast-parser-lexer-shared.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/ast-parser-lexer-shared.c.i
.PHONY : src/ast-parser-lexer-shared.c.i

src/ast-parser-lexer-shared.s: src/ast-parser-lexer-shared.c.s

.PHONY : src/ast-parser-lexer-shared.s

# target to generate assembly for a file
src/ast-parser-lexer-shared.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/ast-parser-lexer-shared.c.s
.PHONY : src/ast-parser-lexer-shared.c.s

src/ast-writer.o: src/ast-writer.c.o

.PHONY : src/ast-writer.o

# target to build an object file
src/ast-writer.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/ast-writer.c.o
.PHONY : src/ast-writer.c.o

src/ast-writer.i: src/ast-writer.c.i

.PHONY : src/ast-writer.i

# target to preprocess a source file
src/ast-writer.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/ast-writer.c.i
.PHONY : src/ast-writer.c.i

src/ast-writer.s: src/ast-writer.c.s

.PHONY : src/ast-writer.s

# target to generate assembly for a file
src/ast-writer.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/ast-writer.c.s
.PHONY : src/ast-writer.c.s

src/ast.o: src/ast.c.o

.PHONY : src/ast.o

# target to build an object file
src/ast.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/ast.c.o
.PHONY : src/ast.c.o

src/ast.i: src/ast.c.i

.PHONY : src/ast.i

# target to preprocess a source file
src/ast.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/ast.c.i
.PHONY : src/ast.c.i

src/ast.s: src/ast.c.s

.PHONY : src/ast.s

# target to generate assembly for a file
src/ast.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/ast.c.s
.PHONY : src/ast.c.s

src/binary-reader-ast.o: src/binary-reader-ast.c.o

.PHONY : src/binary-reader-ast.o

# target to build an object file
src/binary-reader-ast.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-reader-ast.c.o
.PHONY : src/binary-reader-ast.c.o

src/binary-reader-ast.i: src/binary-reader-ast.c.i

.PHONY : src/binary-reader-ast.i

# target to preprocess a source file
src/binary-reader-ast.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-reader-ast.c.i
.PHONY : src/binary-reader-ast.c.i

src/binary-reader-ast.s: src/binary-reader-ast.c.s

.PHONY : src/binary-reader-ast.s

# target to generate assembly for a file
src/binary-reader-ast.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-reader-ast.c.s
.PHONY : src/binary-reader-ast.c.s

src/binary-reader-interpreter.o: src/binary-reader-interpreter.c.o

.PHONY : src/binary-reader-interpreter.o

# target to build an object file
src/binary-reader-interpreter.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-reader-interpreter.c.o
.PHONY : src/binary-reader-interpreter.c.o

src/binary-reader-interpreter.i: src/binary-reader-interpreter.c.i

.PHONY : src/binary-reader-interpreter.i

# target to preprocess a source file
src/binary-reader-interpreter.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-reader-interpreter.c.i
.PHONY : src/binary-reader-interpreter.c.i

src/binary-reader-interpreter.s: src/binary-reader-interpreter.c.s

.PHONY : src/binary-reader-interpreter.s

# target to generate assembly for a file
src/binary-reader-interpreter.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-reader-interpreter.c.s
.PHONY : src/binary-reader-interpreter.c.s

src/binary-reader-objdump.o: src/binary-reader-objdump.c.o

.PHONY : src/binary-reader-objdump.o

# target to build an object file
src/binary-reader-objdump.c.o:
	$(MAKE) -f CMakeFiles/wasmdump.dir/build.make CMakeFiles/wasmdump.dir/src/binary-reader-objdump.c.o
.PHONY : src/binary-reader-objdump.c.o

src/binary-reader-objdump.i: src/binary-reader-objdump.c.i

.PHONY : src/binary-reader-objdump.i

# target to preprocess a source file
src/binary-reader-objdump.c.i:
	$(MAKE) -f CMakeFiles/wasmdump.dir/build.make CMakeFiles/wasmdump.dir/src/binary-reader-objdump.c.i
.PHONY : src/binary-reader-objdump.c.i

src/binary-reader-objdump.s: src/binary-reader-objdump.c.s

.PHONY : src/binary-reader-objdump.s

# target to generate assembly for a file
src/binary-reader-objdump.c.s:
	$(MAKE) -f CMakeFiles/wasmdump.dir/build.make CMakeFiles/wasmdump.dir/src/binary-reader-objdump.c.s
.PHONY : src/binary-reader-objdump.c.s

src/binary-reader-opcnt.o: src/binary-reader-opcnt.c.o

.PHONY : src/binary-reader-opcnt.o

# target to build an object file
src/binary-reader-opcnt.c.o:
	$(MAKE) -f CMakeFiles/wasmopcodecnt.dir/build.make CMakeFiles/wasmopcodecnt.dir/src/binary-reader-opcnt.c.o
.PHONY : src/binary-reader-opcnt.c.o

src/binary-reader-opcnt.i: src/binary-reader-opcnt.c.i

.PHONY : src/binary-reader-opcnt.i

# target to preprocess a source file
src/binary-reader-opcnt.c.i:
	$(MAKE) -f CMakeFiles/wasmopcodecnt.dir/build.make CMakeFiles/wasmopcodecnt.dir/src/binary-reader-opcnt.c.i
.PHONY : src/binary-reader-opcnt.c.i

src/binary-reader-opcnt.s: src/binary-reader-opcnt.c.s

.PHONY : src/binary-reader-opcnt.s

# target to generate assembly for a file
src/binary-reader-opcnt.c.s:
	$(MAKE) -f CMakeFiles/wasmopcodecnt.dir/build.make CMakeFiles/wasmopcodecnt.dir/src/binary-reader-opcnt.c.s
.PHONY : src/binary-reader-opcnt.c.s

src/binary-reader.o: src/binary-reader.c.o

.PHONY : src/binary-reader.o

# target to build an object file
src/binary-reader.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-reader.c.o
.PHONY : src/binary-reader.c.o

src/binary-reader.i: src/binary-reader.c.i

.PHONY : src/binary-reader.i

# target to preprocess a source file
src/binary-reader.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-reader.c.i
.PHONY : src/binary-reader.c.i

src/binary-reader.s: src/binary-reader.c.s

.PHONY : src/binary-reader.s

# target to generate assembly for a file
src/binary-reader.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-reader.c.s
.PHONY : src/binary-reader.c.s

src/binary-writer-spec.o: src/binary-writer-spec.c.o

.PHONY : src/binary-writer-spec.o

# target to build an object file
src/binary-writer-spec.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-writer-spec.c.o
.PHONY : src/binary-writer-spec.c.o

src/binary-writer-spec.i: src/binary-writer-spec.c.i

.PHONY : src/binary-writer-spec.i

# target to preprocess a source file
src/binary-writer-spec.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-writer-spec.c.i
.PHONY : src/binary-writer-spec.c.i

src/binary-writer-spec.s: src/binary-writer-spec.c.s

.PHONY : src/binary-writer-spec.s

# target to generate assembly for a file
src/binary-writer-spec.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-writer-spec.c.s
.PHONY : src/binary-writer-spec.c.s

src/binary-writer.o: src/binary-writer.c.o

.PHONY : src/binary-writer.o

# target to build an object file
src/binary-writer.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-writer.c.o
.PHONY : src/binary-writer.c.o

src/binary-writer.i: src/binary-writer.c.i

.PHONY : src/binary-writer.i

# target to preprocess a source file
src/binary-writer.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-writer.c.i
.PHONY : src/binary-writer.c.i

src/binary-writer.s: src/binary-writer.c.s

.PHONY : src/binary-writer.s

# target to generate assembly for a file
src/binary-writer.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary-writer.c.s
.PHONY : src/binary-writer.c.s

src/binary.o: src/binary.c.o

.PHONY : src/binary.o

# target to build an object file
src/binary.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary.c.o
.PHONY : src/binary.c.o

src/binary.i: src/binary.c.i

.PHONY : src/binary.i

# target to preprocess a source file
src/binary.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary.c.i
.PHONY : src/binary.c.i

src/binary.s: src/binary.c.s

.PHONY : src/binary.s

# target to generate assembly for a file
src/binary.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binary.c.s
.PHONY : src/binary.c.s

src/binding-hash.o: src/binding-hash.c.o

.PHONY : src/binding-hash.o

# target to build an object file
src/binding-hash.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binding-hash.c.o
.PHONY : src/binding-hash.c.o

src/binding-hash.i: src/binding-hash.c.i

.PHONY : src/binding-hash.i

# target to preprocess a source file
src/binding-hash.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binding-hash.c.i
.PHONY : src/binding-hash.c.i

src/binding-hash.s: src/binding-hash.c.s

.PHONY : src/binding-hash.s

# target to generate assembly for a file
src/binding-hash.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/binding-hash.c.s
.PHONY : src/binding-hash.c.s

src/common.o: src/common.c.o

.PHONY : src/common.o

# target to build an object file
src/common.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/common.c.o
.PHONY : src/common.c.o

src/common.i: src/common.c.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/common.c.i
.PHONY : src/common.c.i

src/common.s: src/common.c.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/common.c.s
.PHONY : src/common.c.s

src/config.o: src/config.c.o

.PHONY : src/config.o

# target to build an object file
src/config.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/config.c.o
.PHONY : src/config.c.o

src/config.i: src/config.c.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/config.c.i
.PHONY : src/config.c.i

src/config.s: src/config.c.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/config.c.s
.PHONY : src/config.c.s

src/generate-names.o: src/generate-names.c.o

.PHONY : src/generate-names.o

# target to build an object file
src/generate-names.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/generate-names.c.o
.PHONY : src/generate-names.c.o

src/generate-names.i: src/generate-names.c.i

.PHONY : src/generate-names.i

# target to preprocess a source file
src/generate-names.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/generate-names.c.i
.PHONY : src/generate-names.c.i

src/generate-names.s: src/generate-names.c.s

.PHONY : src/generate-names.s

# target to generate assembly for a file
src/generate-names.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/generate-names.c.s
.PHONY : src/generate-names.c.s

src/interpreter.o: src/interpreter.c.o

.PHONY : src/interpreter.o

# target to build an object file
src/interpreter.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/interpreter.c.o
.PHONY : src/interpreter.c.o

src/interpreter.i: src/interpreter.c.i

.PHONY : src/interpreter.i

# target to preprocess a source file
src/interpreter.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/interpreter.c.i
.PHONY : src/interpreter.c.i

src/interpreter.s: src/interpreter.c.s

.PHONY : src/interpreter.s

# target to generate assembly for a file
src/interpreter.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/interpreter.c.s
.PHONY : src/interpreter.c.s

src/literal.o: src/literal.c.o

.PHONY : src/literal.o

# target to build an object file
src/literal.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/literal.c.o
	$(MAKE) -f CMakeFiles/hexfloat_test.dir/build.make CMakeFiles/hexfloat_test.dir/src/literal.c.o
.PHONY : src/literal.c.o

src/literal.i: src/literal.c.i

.PHONY : src/literal.i

# target to preprocess a source file
src/literal.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/literal.c.i
	$(MAKE) -f CMakeFiles/hexfloat_test.dir/build.make CMakeFiles/hexfloat_test.dir/src/literal.c.i
.PHONY : src/literal.c.i

src/literal.s: src/literal.c.s

.PHONY : src/literal.s

# target to generate assembly for a file
src/literal.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/literal.c.s
	$(MAKE) -f CMakeFiles/hexfloat_test.dir/build.make CMakeFiles/hexfloat_test.dir/src/literal.c.s
.PHONY : src/literal.c.s

src/option-parser.o: src/option-parser.c.o

.PHONY : src/option-parser.o

# target to build an object file
src/option-parser.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/option-parser.c.o
.PHONY : src/option-parser.c.o

src/option-parser.i: src/option-parser.c.i

.PHONY : src/option-parser.i

# target to preprocess a source file
src/option-parser.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/option-parser.c.i
.PHONY : src/option-parser.c.i

src/option-parser.s: src/option-parser.c.s

.PHONY : src/option-parser.s

# target to generate assembly for a file
src/option-parser.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/option-parser.c.s
.PHONY : src/option-parser.c.s

src/resolve-names.o: src/resolve-names.c.o

.PHONY : src/resolve-names.o

# target to build an object file
src/resolve-names.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/resolve-names.c.o
.PHONY : src/resolve-names.c.o

src/resolve-names.i: src/resolve-names.c.i

.PHONY : src/resolve-names.i

# target to preprocess a source file
src/resolve-names.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/resolve-names.c.i
.PHONY : src/resolve-names.c.i

src/resolve-names.s: src/resolve-names.c.s

.PHONY : src/resolve-names.s

# target to generate assembly for a file
src/resolve-names.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/resolve-names.c.s
.PHONY : src/resolve-names.c.s

src/stack-allocator.o: src/stack-allocator.c.o

.PHONY : src/stack-allocator.o

# target to build an object file
src/stack-allocator.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/stack-allocator.c.o
.PHONY : src/stack-allocator.c.o

src/stack-allocator.i: src/stack-allocator.c.i

.PHONY : src/stack-allocator.i

# target to preprocess a source file
src/stack-allocator.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/stack-allocator.c.i
.PHONY : src/stack-allocator.c.i

src/stack-allocator.s: src/stack-allocator.c.s

.PHONY : src/stack-allocator.s

# target to generate assembly for a file
src/stack-allocator.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/stack-allocator.c.s
.PHONY : src/stack-allocator.c.s

src/stream.o: src/stream.c.o

.PHONY : src/stream.o

# target to build an object file
src/stream.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/stream.c.o
.PHONY : src/stream.c.o

src/stream.i: src/stream.c.i

.PHONY : src/stream.i

# target to preprocess a source file
src/stream.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/stream.c.i
.PHONY : src/stream.c.i

src/stream.s: src/stream.c.s

.PHONY : src/stream.s

# target to generate assembly for a file
src/stream.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/stream.c.s
.PHONY : src/stream.c.s

src/tools/wasm-interp.o: src/tools/wasm-interp.c.o

.PHONY : src/tools/wasm-interp.o

# target to build an object file
src/tools/wasm-interp.c.o:
	$(MAKE) -f CMakeFiles/wasm-interp.dir/build.make CMakeFiles/wasm-interp.dir/src/tools/wasm-interp.c.o
.PHONY : src/tools/wasm-interp.c.o

src/tools/wasm-interp.i: src/tools/wasm-interp.c.i

.PHONY : src/tools/wasm-interp.i

# target to preprocess a source file
src/tools/wasm-interp.c.i:
	$(MAKE) -f CMakeFiles/wasm-interp.dir/build.make CMakeFiles/wasm-interp.dir/src/tools/wasm-interp.c.i
.PHONY : src/tools/wasm-interp.c.i

src/tools/wasm-interp.s: src/tools/wasm-interp.c.s

.PHONY : src/tools/wasm-interp.s

# target to generate assembly for a file
src/tools/wasm-interp.c.s:
	$(MAKE) -f CMakeFiles/wasm-interp.dir/build.make CMakeFiles/wasm-interp.dir/src/tools/wasm-interp.c.s
.PHONY : src/tools/wasm-interp.c.s

src/tools/wasm2wast.o: src/tools/wasm2wast.c.o

.PHONY : src/tools/wasm2wast.o

# target to build an object file
src/tools/wasm2wast.c.o:
	$(MAKE) -f CMakeFiles/wasm2wast.dir/build.make CMakeFiles/wasm2wast.dir/src/tools/wasm2wast.c.o
.PHONY : src/tools/wasm2wast.c.o

src/tools/wasm2wast.i: src/tools/wasm2wast.c.i

.PHONY : src/tools/wasm2wast.i

# target to preprocess a source file
src/tools/wasm2wast.c.i:
	$(MAKE) -f CMakeFiles/wasm2wast.dir/build.make CMakeFiles/wasm2wast.dir/src/tools/wasm2wast.c.i
.PHONY : src/tools/wasm2wast.c.i

src/tools/wasm2wast.s: src/tools/wasm2wast.c.s

.PHONY : src/tools/wasm2wast.s

# target to generate assembly for a file
src/tools/wasm2wast.c.s:
	$(MAKE) -f CMakeFiles/wasm2wast.dir/build.make CMakeFiles/wasm2wast.dir/src/tools/wasm2wast.c.s
.PHONY : src/tools/wasm2wast.c.s

src/tools/wasmdump.o: src/tools/wasmdump.c.o

.PHONY : src/tools/wasmdump.o

# target to build an object file
src/tools/wasmdump.c.o:
	$(MAKE) -f CMakeFiles/wasmdump.dir/build.make CMakeFiles/wasmdump.dir/src/tools/wasmdump.c.o
.PHONY : src/tools/wasmdump.c.o

src/tools/wasmdump.i: src/tools/wasmdump.c.i

.PHONY : src/tools/wasmdump.i

# target to preprocess a source file
src/tools/wasmdump.c.i:
	$(MAKE) -f CMakeFiles/wasmdump.dir/build.make CMakeFiles/wasmdump.dir/src/tools/wasmdump.c.i
.PHONY : src/tools/wasmdump.c.i

src/tools/wasmdump.s: src/tools/wasmdump.c.s

.PHONY : src/tools/wasmdump.s

# target to generate assembly for a file
src/tools/wasmdump.c.s:
	$(MAKE) -f CMakeFiles/wasmdump.dir/build.make CMakeFiles/wasmdump.dir/src/tools/wasmdump.c.s
.PHONY : src/tools/wasmdump.c.s

src/tools/wasmopcodecnt.o: src/tools/wasmopcodecnt.c.o

.PHONY : src/tools/wasmopcodecnt.o

# target to build an object file
src/tools/wasmopcodecnt.c.o:
	$(MAKE) -f CMakeFiles/wasmopcodecnt.dir/build.make CMakeFiles/wasmopcodecnt.dir/src/tools/wasmopcodecnt.c.o
.PHONY : src/tools/wasmopcodecnt.c.o

src/tools/wasmopcodecnt.i: src/tools/wasmopcodecnt.c.i

.PHONY : src/tools/wasmopcodecnt.i

# target to preprocess a source file
src/tools/wasmopcodecnt.c.i:
	$(MAKE) -f CMakeFiles/wasmopcodecnt.dir/build.make CMakeFiles/wasmopcodecnt.dir/src/tools/wasmopcodecnt.c.i
.PHONY : src/tools/wasmopcodecnt.c.i

src/tools/wasmopcodecnt.s: src/tools/wasmopcodecnt.c.s

.PHONY : src/tools/wasmopcodecnt.s

# target to generate assembly for a file
src/tools/wasmopcodecnt.c.s:
	$(MAKE) -f CMakeFiles/wasmopcodecnt.dir/build.make CMakeFiles/wasmopcodecnt.dir/src/tools/wasmopcodecnt.c.s
.PHONY : src/tools/wasmopcodecnt.c.s

src/tools/wast-desugar.o: src/tools/wast-desugar.c.o

.PHONY : src/tools/wast-desugar.o

# target to build an object file
src/tools/wast-desugar.c.o:
	$(MAKE) -f CMakeFiles/wast-desugar.dir/build.make CMakeFiles/wast-desugar.dir/src/tools/wast-desugar.c.o
.PHONY : src/tools/wast-desugar.c.o

src/tools/wast-desugar.i: src/tools/wast-desugar.c.i

.PHONY : src/tools/wast-desugar.i

# target to preprocess a source file
src/tools/wast-desugar.c.i:
	$(MAKE) -f CMakeFiles/wast-desugar.dir/build.make CMakeFiles/wast-desugar.dir/src/tools/wast-desugar.c.i
.PHONY : src/tools/wast-desugar.c.i

src/tools/wast-desugar.s: src/tools/wast-desugar.c.s

.PHONY : src/tools/wast-desugar.s

# target to generate assembly for a file
src/tools/wast-desugar.c.s:
	$(MAKE) -f CMakeFiles/wast-desugar.dir/build.make CMakeFiles/wast-desugar.dir/src/tools/wast-desugar.c.s
.PHONY : src/tools/wast-desugar.c.s

src/tools/wast2wasm.o: src/tools/wast2wasm.c.o

.PHONY : src/tools/wast2wasm.o

# target to build an object file
src/tools/wast2wasm.c.o:
	$(MAKE) -f CMakeFiles/wast2wasm.dir/build.make CMakeFiles/wast2wasm.dir/src/tools/wast2wasm.c.o
.PHONY : src/tools/wast2wasm.c.o

src/tools/wast2wasm.i: src/tools/wast2wasm.c.i

.PHONY : src/tools/wast2wasm.i

# target to preprocess a source file
src/tools/wast2wasm.c.i:
	$(MAKE) -f CMakeFiles/wast2wasm.dir/build.make CMakeFiles/wast2wasm.dir/src/tools/wast2wasm.c.i
.PHONY : src/tools/wast2wasm.c.i

src/tools/wast2wasm.s: src/tools/wast2wasm.c.s

.PHONY : src/tools/wast2wasm.s

# target to generate assembly for a file
src/tools/wast2wasm.c.s:
	$(MAKE) -f CMakeFiles/wast2wasm.dir/build.make CMakeFiles/wast2wasm.dir/src/tools/wast2wasm.c.s
.PHONY : src/tools/wast2wasm.c.s

src/validator.o: src/validator.c.o

.PHONY : src/validator.o

# target to build an object file
src/validator.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/validator.c.o
.PHONY : src/validator.c.o

src/validator.i: src/validator.c.i

.PHONY : src/validator.i

# target to preprocess a source file
src/validator.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/validator.c.i
.PHONY : src/validator.c.i

src/validator.s: src/validator.c.s

.PHONY : src/validator.s

# target to generate assembly for a file
src/validator.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/validator.c.s
.PHONY : src/validator.c.s

src/vector.o: src/vector.c.o

.PHONY : src/vector.o

# target to build an object file
src/vector.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/vector.c.o
.PHONY : src/vector.c.o

src/vector.i: src/vector.c.i

.PHONY : src/vector.i

# target to preprocess a source file
src/vector.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/vector.c.i
.PHONY : src/vector.c.i

src/vector.s: src/vector.c.s

.PHONY : src/vector.s

# target to generate assembly for a file
src/vector.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/vector.c.s
.PHONY : src/vector.c.s

src/writer.o: src/writer.c.o

.PHONY : src/writer.o

# target to build an object file
src/writer.c.o:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/writer.c.o
.PHONY : src/writer.c.o

src/writer.i: src/writer.c.i

.PHONY : src/writer.i

# target to preprocess a source file
src/writer.c.i:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/writer.c.i
.PHONY : src/writer.c.i

src/writer.s: src/writer.c.s

.PHONY : src/writer.s

# target to generate assembly for a file
src/writer.c.s:
	$(MAKE) -f CMakeFiles/libwasm.dir/build.make CMakeFiles/libwasm.dir/src/writer.c.s
.PHONY : src/writer.c.s

test/hexfloat.o: test/hexfloat.cc.o

.PHONY : test/hexfloat.o

# target to build an object file
test/hexfloat.cc.o:
	$(MAKE) -f CMakeFiles/hexfloat_test.dir/build.make CMakeFiles/hexfloat_test.dir/test/hexfloat.cc.o
.PHONY : test/hexfloat.cc.o

test/hexfloat.i: test/hexfloat.cc.i

.PHONY : test/hexfloat.i

# target to preprocess a source file
test/hexfloat.cc.i:
	$(MAKE) -f CMakeFiles/hexfloat_test.dir/build.make CMakeFiles/hexfloat_test.dir/test/hexfloat.cc.i
.PHONY : test/hexfloat.cc.i

test/hexfloat.s: test/hexfloat.cc.s

.PHONY : test/hexfloat.s

# target to generate assembly for a file
test/hexfloat.cc.s:
	$(MAKE) -f CMakeFiles/hexfloat_test.dir/build.make CMakeFiles/hexfloat_test.dir/test/hexfloat.cc.s
.PHONY : test/hexfloat.cc.s

third_party/gtest/googletest/src/gtest-all.o: third_party/gtest/googletest/src/gtest-all.cc.o

.PHONY : third_party/gtest/googletest/src/gtest-all.o

# target to build an object file
third_party/gtest/googletest/src/gtest-all.cc.o:
	$(MAKE) -f CMakeFiles/hexfloat_test.dir/build.make CMakeFiles/hexfloat_test.dir/third_party/gtest/googletest/src/gtest-all.cc.o
.PHONY : third_party/gtest/googletest/src/gtest-all.cc.o

third_party/gtest/googletest/src/gtest-all.i: third_party/gtest/googletest/src/gtest-all.cc.i

.PHONY : third_party/gtest/googletest/src/gtest-all.i

# target to preprocess a source file
third_party/gtest/googletest/src/gtest-all.cc.i:
	$(MAKE) -f CMakeFiles/hexfloat_test.dir/build.make CMakeFiles/hexfloat_test.dir/third_party/gtest/googletest/src/gtest-all.cc.i
.PHONY : third_party/gtest/googletest/src/gtest-all.cc.i

third_party/gtest/googletest/src/gtest-all.s: third_party/gtest/googletest/src/gtest-all.cc.s

.PHONY : third_party/gtest/googletest/src/gtest-all.s

# target to generate assembly for a file
third_party/gtest/googletest/src/gtest-all.cc.s:
	$(MAKE) -f CMakeFiles/hexfloat_test.dir/build.make CMakeFiles/hexfloat_test.dir/third_party/gtest/googletest/src/gtest-all.cc.s
.PHONY : third_party/gtest/googletest/src/gtest-all.cc.s

third_party/gtest/googletest/src/gtest_main.o: third_party/gtest/googletest/src/gtest_main.cc.o

.PHONY : third_party/gtest/googletest/src/gtest_main.o

# target to build an object file
third_party/gtest/googletest/src/gtest_main.cc.o:
	$(MAKE) -f CMakeFiles/hexfloat_test.dir/build.make CMakeFiles/hexfloat_test.dir/third_party/gtest/googletest/src/gtest_main.cc.o
.PHONY : third_party/gtest/googletest/src/gtest_main.cc.o

third_party/gtest/googletest/src/gtest_main.i: third_party/gtest/googletest/src/gtest_main.cc.i

.PHONY : third_party/gtest/googletest/src/gtest_main.i

# target to preprocess a source file
third_party/gtest/googletest/src/gtest_main.cc.i:
	$(MAKE) -f CMakeFiles/hexfloat_test.dir/build.make CMakeFiles/hexfloat_test.dir/third_party/gtest/googletest/src/gtest_main.cc.i
.PHONY : third_party/gtest/googletest/src/gtest_main.cc.i

third_party/gtest/googletest/src/gtest_main.s: third_party/gtest/googletest/src/gtest_main.cc.s

.PHONY : third_party/gtest/googletest/src/gtest_main.s

# target to generate assembly for a file
third_party/gtest/googletest/src/gtest_main.cc.s:
	$(MAKE) -f CMakeFiles/hexfloat_test.dir/build.make CMakeFiles/hexfloat_test.dir/third_party/gtest/googletest/src/gtest_main.cc.s
.PHONY : third_party/gtest/googletest/src/gtest_main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... install/local"
	@echo "... run-tests"
	@echo "... edit_cache"
	@echo "... everything"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... WASM_AST_LEXER_GEN_C"
	@echo "... wast-desugar"
	@echo "... wasm2wast"
	@echo "... wast2wasm"
	@echo "... libwasm"
	@echo "... hexfloat_test"
	@echo "... wasmopcodecnt"
	@echo "... wasm-interp"
	@echo "... wasmdump"
	@echo "... ast-lexer-gen.o"
	@echo "... ast-lexer-gen.i"
	@echo "... ast-lexer-gen.s"
	@echo "... ast-parser-gen.o"
	@echo "... ast-parser-gen.i"
	@echo "... ast-parser-gen.s"
	@echo "... src/allocator.o"
	@echo "... src/allocator.i"
	@echo "... src/allocator.s"
	@echo "... src/apply-names.o"
	@echo "... src/apply-names.i"
	@echo "... src/apply-names.s"
	@echo "... src/ast-parser-lexer-shared.o"
	@echo "... src/ast-parser-lexer-shared.i"
	@echo "... src/ast-parser-lexer-shared.s"
	@echo "... src/ast-writer.o"
	@echo "... src/ast-writer.i"
	@echo "... src/ast-writer.s"
	@echo "... src/ast.o"
	@echo "... src/ast.i"
	@echo "... src/ast.s"
	@echo "... src/binary-reader-ast.o"
	@echo "... src/binary-reader-ast.i"
	@echo "... src/binary-reader-ast.s"
	@echo "... src/binary-reader-interpreter.o"
	@echo "... src/binary-reader-interpreter.i"
	@echo "... src/binary-reader-interpreter.s"
	@echo "... src/binary-reader-objdump.o"
	@echo "... src/binary-reader-objdump.i"
	@echo "... src/binary-reader-objdump.s"
	@echo "... src/binary-reader-opcnt.o"
	@echo "... src/binary-reader-opcnt.i"
	@echo "... src/binary-reader-opcnt.s"
	@echo "... src/binary-reader.o"
	@echo "... src/binary-reader.i"
	@echo "... src/binary-reader.s"
	@echo "... src/binary-writer-spec.o"
	@echo "... src/binary-writer-spec.i"
	@echo "... src/binary-writer-spec.s"
	@echo "... src/binary-writer.o"
	@echo "... src/binary-writer.i"
	@echo "... src/binary-writer.s"
	@echo "... src/binary.o"
	@echo "... src/binary.i"
	@echo "... src/binary.s"
	@echo "... src/binding-hash.o"
	@echo "... src/binding-hash.i"
	@echo "... src/binding-hash.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/generate-names.o"
	@echo "... src/generate-names.i"
	@echo "... src/generate-names.s"
	@echo "... src/interpreter.o"
	@echo "... src/interpreter.i"
	@echo "... src/interpreter.s"
	@echo "... src/literal.o"
	@echo "... src/literal.i"
	@echo "... src/literal.s"
	@echo "... src/option-parser.o"
	@echo "... src/option-parser.i"
	@echo "... src/option-parser.s"
	@echo "... src/resolve-names.o"
	@echo "... src/resolve-names.i"
	@echo "... src/resolve-names.s"
	@echo "... src/stack-allocator.o"
	@echo "... src/stack-allocator.i"
	@echo "... src/stack-allocator.s"
	@echo "... src/stream.o"
	@echo "... src/stream.i"
	@echo "... src/stream.s"
	@echo "... src/tools/wasm-interp.o"
	@echo "... src/tools/wasm-interp.i"
	@echo "... src/tools/wasm-interp.s"
	@echo "... src/tools/wasm2wast.o"
	@echo "... src/tools/wasm2wast.i"
	@echo "... src/tools/wasm2wast.s"
	@echo "... src/tools/wasmdump.o"
	@echo "... src/tools/wasmdump.i"
	@echo "... src/tools/wasmdump.s"
	@echo "... src/tools/wasmopcodecnt.o"
	@echo "... src/tools/wasmopcodecnt.i"
	@echo "... src/tools/wasmopcodecnt.s"
	@echo "... src/tools/wast-desugar.o"
	@echo "... src/tools/wast-desugar.i"
	@echo "... src/tools/wast-desugar.s"
	@echo "... src/tools/wast2wasm.o"
	@echo "... src/tools/wast2wasm.i"
	@echo "... src/tools/wast2wasm.s"
	@echo "... src/validator.o"
	@echo "... src/validator.i"
	@echo "... src/validator.s"
	@echo "... src/vector.o"
	@echo "... src/vector.i"
	@echo "... src/vector.s"
	@echo "... src/writer.o"
	@echo "... src/writer.i"
	@echo "... src/writer.s"
	@echo "... test/hexfloat.o"
	@echo "... test/hexfloat.i"
	@echo "... test/hexfloat.s"
	@echo "... third_party/gtest/googletest/src/gtest-all.o"
	@echo "... third_party/gtest/googletest/src/gtest-all.i"
	@echo "... third_party/gtest/googletest/src/gtest-all.s"
	@echo "... third_party/gtest/googletest/src/gtest_main.o"
	@echo "... third_party/gtest/googletest/src/gtest_main.i"
	@echo "... third_party/gtest/googletest/src/gtest_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

