;;-------------------------------------------------------------------------------------------------------

;; Copyright (C) Microsoft. All rights reserved.

;; Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.

;;-------------------------------------------------------------------------------------------------------


(module
    (func
        (export  "func_i32x4_0")
        (result  i32)
        (local  i32x4)
        (set_local
            0
            (i32x4.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
            )
        )
        (i32x4.extract
            (get_local  0)
            (i32.const  0)
        )
    )
    (func
        (export  "func_i32x4_1")
        (result  i32)
        (local  i32x4)
        (set_local
            0
            (i32x4.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
            )
        )
        (i32x4.extract
            (get_local  0)
            (i32.const  1)
        )
    )
    (func
        (export  "func_i32x4_2")
        (result  i32)
        (local  i32x4)
        (set_local
            0
            (i32x4.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
            )
        )
        (i32x4.extract
            (get_local  0)
            (i32.const  2)
        )
    )
    (func
        (export  "func_i32x4_3")
        (result  i32)
        (local  i32x4)
        (set_local
            0
            (i32x4.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
            )
        )
        (i32x4.extract
            (get_local  0)
            (i32.const  3)
        )
    )
    (func
        (export  "func_i16x8_0")
        (result  i32)
        (local  i16x8)
        (set_local
            0
            (i16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (i16x8.extract
            (get_local  0)
            (i32.const  0)
        )
    )
    (func
        (export  "func_i16x8_1")
        (result  i32)
        (local  i16x8)
        (set_local
            0
            (i16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (i16x8.extract
            (get_local  0)
            (i32.const  1)
        )
    )
    (func
        (export  "func_i16x8_2")
        (result  i32)
        (local  i16x8)
        (set_local
            0
            (i16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (i16x8.extract
            (get_local  0)
            (i32.const  2)
        )
    )
    (func
        (export  "func_i16x8_3")
        (result  i32)
        (local  i16x8)
        (set_local
            0
            (i16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (i16x8.extract
            (get_local  0)
            (i32.const  3)
        )
    )
    (func
        (export  "func_i16x8_4")
        (result  i32)
        (local  i16x8)
        (set_local
            0
            (i16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (i16x8.extract
            (get_local  0)
            (i32.const  4)
        )
    )
    (func
        (export  "func_i16x8_5")
        (result  i32)
        (local  i16x8)
        (set_local
            0
            (i16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (i16x8.extract
            (get_local  0)
            (i32.const  5)
        )
    )
    (func
        (export  "func_i16x8_6")
        (result  i32)
        (local  i16x8)
        (set_local
            0
            (i16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (i16x8.extract
            (get_local  0)
            (i32.const  6)
        )
    )
    (func
        (export  "func_i16x8_7")
        (result  i32)
        (local  i16x8)
        (set_local
            0
            (i16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (i16x8.extract
            (get_local  0)
            (i32.const  7)
        )
    )
    (func
        (export  "func_i8x16_0")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  0)
        )
    )
    (func
        (export  "func_i8x16_1")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  1)
        )
    )
    (func
        (export  "func_i8x16_2")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  2)
        )
    )
    (func
        (export  "func_i8x16_3")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  3)
        )
    )
    (func
        (export  "func_i8x16_4")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  4)
        )
    )
    (func
        (export  "func_i8x16_5")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  5)
        )
    )
    (func
        (export  "func_i8x16_6")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  6)
        )
    )
    (func
        (export  "func_i8x16_7")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  7)
        )
    )
    (func
        (export  "func_i8x16_8")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  8)
        )
    )
    (func
        (export  "func_i8x16_9")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  9)
        )
    )
    (func
        (export  "func_i8x16_10")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  10)
        )
    )
    (func
        (export  "func_i8x16_11")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  11)
        )
    )
    (func
        (export  "func_i8x16_12")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  12)
        )
    )
    (func
        (export  "func_i8x16_13")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  13)
        )
    )
    (func
        (export  "func_i8x16_14")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  14)
        )
    )
    (func
        (export  "func_i8x16_15")
        (result  i32)
        (local  i8x16)
        (set_local
            0
            (i8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (i8x16.extract
            (get_local  0)
            (i32.const  15)
        )
    )
    (func
        (export  "func_b32x4_0")
        (result  i32)
        (local  b32x4)
        (set_local
            0
            (b32x4.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
            )
        )
        (b32x4.extract
            (get_local  0)
            (i32.const  0)
        )
    )
    (func
        (export  "func_b32x4_1")
        (result  i32)
        (local  b32x4)
        (set_local
            0
            (b32x4.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
            )
        )
        (b32x4.extract
            (get_local  0)
            (i32.const  1)
        )
    )
    (func
        (export  "func_b32x4_2")
        (result  i32)
        (local  b32x4)
        (set_local
            0
            (b32x4.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
            )
        )
        (b32x4.extract
            (get_local  0)
            (i32.const  2)
        )
    )
    (func
        (export  "func_b32x4_3")
        (result  i32)
        (local  b32x4)
        (set_local
            0
            (b32x4.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
            )
        )
        (b32x4.extract
            (get_local  0)
            (i32.const  3)
        )
    )
    (func
        (export  "func_b16x8_0")
        (result  i32)
        (local  b16x8)
        (set_local
            0
            (b16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (b16x8.extract
            (get_local  0)
            (i32.const  0)
        )
    )
    (func
        (export  "func_b16x8_1")
        (result  i32)
        (local  b16x8)
        (set_local
            0
            (b16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (b16x8.extract
            (get_local  0)
            (i32.const  1)
        )
    )
    (func
        (export  "func_b16x8_2")
        (result  i32)
        (local  b16x8)
        (set_local
            0
            (b16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (b16x8.extract
            (get_local  0)
            (i32.const  2)
        )
    )
    (func
        (export  "func_b16x8_3")
        (result  i32)
        (local  b16x8)
        (set_local
            0
            (b16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (b16x8.extract
            (get_local  0)
            (i32.const  3)
        )
    )
    (func
        (export  "func_b16x8_4")
        (result  i32)
        (local  b16x8)
        (set_local
            0
            (b16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (b16x8.extract
            (get_local  0)
            (i32.const  4)
        )
    )
    (func
        (export  "func_b16x8_5")
        (result  i32)
        (local  b16x8)
        (set_local
            0
            (b16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (b16x8.extract
            (get_local  0)
            (i32.const  5)
        )
    )
    (func
        (export  "func_b16x8_6")
        (result  i32)
        (local  b16x8)
        (set_local
            0
            (b16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (b16x8.extract
            (get_local  0)
            (i32.const  6)
        )
    )
    (func
        (export  "func_b16x8_7")
        (result  i32)
        (local  b16x8)
        (set_local
            0
            (b16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (b16x8.extract
            (get_local  0)
            (i32.const  7)
        )
    )
    (func
        (export  "func_b8x16_0")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  0)
        )
    )
    (func
        (export  "func_b8x16_1")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  1)
        )
    )
    (func
        (export  "func_b8x16_2")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  2)
        )
    )
    (func
        (export  "func_b8x16_3")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  3)
        )
    )
    (func
        (export  "func_b8x16_4")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  4)
        )
    )
    (func
        (export  "func_b8x16_5")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  5)
        )
    )
    (func
        (export  "func_b8x16_6")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  6)
        )
    )
    (func
        (export  "func_b8x16_7")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  7)
        )
    )
    (func
        (export  "func_b8x16_8")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  8)
        )
    )
    (func
        (export  "func_b8x16_9")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  9)
        )
    )
    (func
        (export  "func_b8x16_10")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  10)
        )
    )
    (func
        (export  "func_b8x16_11")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  11)
        )
    )
    (func
        (export  "func_b8x16_12")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  12)
        )
    )
    (func
        (export  "func_b8x16_13")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  13)
        )
    )
    (func
        (export  "func_b8x16_14")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  14)
        )
    )
    (func
        (export  "func_b8x16_15")
        (result  i32)
        (local  b8x16)
        (set_local
            0
            (b8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (b8x16.extract
            (get_local  0)
            (i32.const  15)
        )
    )
    (func
        (export  "func_u32x4_0")
        (result  i32)
        (local  u32x4)
        (set_local
            0
            (u32x4.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
            )
        )
        (u32x4.extract
            (get_local  0)
            (i32.const  0)
        )
    )
    (func
        (export  "func_u32x4_1")
        (result  i32)
        (local  u32x4)
        (set_local
            0
            (u32x4.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
            )
        )
        (u32x4.extract
            (get_local  0)
            (i32.const  1)
        )
    )
    (func
        (export  "func_u32x4_2")
        (result  i32)
        (local  u32x4)
        (set_local
            0
            (u32x4.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
            )
        )
        (u32x4.extract
            (get_local  0)
            (i32.const  2)
        )
    )
    (func
        (export  "func_u32x4_3")
        (result  i32)
        (local  u32x4)
        (set_local
            0
            (u32x4.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
            )
        )
        (u32x4.extract
            (get_local  0)
            (i32.const  3)
        )
    )
    (func
        (export  "func_u16x8_0")
        (result  i32)
        (local  u16x8)
        (set_local
            0
            (u16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (u16x8.extract
            (get_local  0)
            (i32.const  0)
        )
    )
    (func
        (export  "func_u16x8_1")
        (result  i32)
        (local  u16x8)
        (set_local
            0
            (u16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (u16x8.extract
            (get_local  0)
            (i32.const  1)
        )
    )
    (func
        (export  "func_u16x8_2")
        (result  i32)
        (local  u16x8)
        (set_local
            0
            (u16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (u16x8.extract
            (get_local  0)
            (i32.const  2)
        )
    )
    (func
        (export  "func_u16x8_3")
        (result  i32)
        (local  u16x8)
        (set_local
            0
            (u16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (u16x8.extract
            (get_local  0)
            (i32.const  3)
        )
    )
    (func
        (export  "func_u16x8_4")
        (result  i32)
        (local  u16x8)
        (set_local
            0
            (u16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (u16x8.extract
            (get_local  0)
            (i32.const  4)
        )
    )
    (func
        (export  "func_u16x8_5")
        (result  i32)
        (local  u16x8)
        (set_local
            0
            (u16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (u16x8.extract
            (get_local  0)
            (i32.const  5)
        )
    )
    (func
        (export  "func_u16x8_6")
        (result  i32)
        (local  u16x8)
        (set_local
            0
            (u16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (u16x8.extract
            (get_local  0)
            (i32.const  6)
        )
    )
    (func
        (export  "func_u16x8_7")
        (result  i32)
        (local  u16x8)
        (set_local
            0
            (u16x8.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
            )
        )
        (u16x8.extract
            (get_local  0)
            (i32.const  7)
        )
    )
    (func
        (export  "func_u8x16_0")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  0)
        )
    )
    (func
        (export  "func_u8x16_1")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  1)
        )
    )
    (func
        (export  "func_u8x16_2")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  2)
        )
    )
    (func
        (export  "func_u8x16_3")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  3)
        )
    )
    (func
        (export  "func_u8x16_4")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  4)
        )
    )
    (func
        (export  "func_u8x16_5")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  5)
        )
    )
    (func
        (export  "func_u8x16_6")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  6)
        )
    )
    (func
        (export  "func_u8x16_7")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  7)
        )
    )
    (func
        (export  "func_u8x16_8")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  8)
        )
    )
    (func
        (export  "func_u8x16_9")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  9)
        )
    )
    (func
        (export  "func_u8x16_10")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  10)
        )
    )
    (func
        (export  "func_u8x16_11")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  11)
        )
    )
    (func
        (export  "func_u8x16_12")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  12)
        )
    )
    (func
        (export  "func_u8x16_13")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  13)
        )
    )
    (func
        (export  "func_u8x16_14")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  14)
        )
    )
    (func
        (export  "func_u8x16_15")
        (result  i32)
        (local  u8x16)
        (set_local
            0
            (u8x16.build
                (i32.const  1)
                (i32.const  2)
                (i32.const  3)
                (i32.const  4)
                (i32.const  5)
                (i32.const  6)
                (i32.const  7)
                (i32.const  8)
                (i32.const  9)
                (i32.const  10)
                (i32.const  11)
                (i32.const  12)
                (i32.const  13)
                (i32.const  14)
                (i32.const  15)
                (i32.const  16)
            )
        )
        (u8x16.extract
            (get_local  0)
            (i32.const  15)
        )
    )
)
